// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkJlWDBhpJTtN1nmUtVcAFQS_GHhCYoE',
    appId: '1:517958385331:web:9c338d3275d88fbc753ac6',
    messagingSenderId: '517958385331',
    projectId: 'calendar-schedule-shk-230304',
    authDomain: 'calendar-schedule-shk-230304.firebaseapp.com',
    storageBucket: 'calendar-schedule-shk-230304.appspot.com',
    measurementId: 'G-RFB5XZ0KES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgHpaoo8rmPgsamBrUVMlMzZ1T3UBPFc',
    appId: '1:517958385331:android:df4ad28ee45b1962753ac6',
    messagingSenderId: '517958385331',
    projectId: 'calendar-schedule-shk-230304',
    storageBucket: 'calendar-schedule-shk-230304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT0t6mo-EJlIOMRn6e6hcHr3lR5_4meoc',
    appId: '1:517958385331:ios:37885f7ca86215d9753ac6',
    messagingSenderId: '517958385331',
    projectId: 'calendar-schedule-shk-230304',
    storageBucket: 'calendar-schedule-shk-230304.appspot.com',
    iosClientId: '517958385331-t5cdqjpd62474oimv4s5dv4hbhuodi90.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT0t6mo-EJlIOMRn6e6hcHr3lR5_4meoc',
    appId: '1:517958385331:ios:c6742923542f3682753ac6',
    messagingSenderId: '517958385331',
    projectId: 'calendar-schedule-shk-230304',
    storageBucket: 'calendar-schedule-shk-230304.appspot.com',
    iosClientId: '517958385331-rtg548966kt65i4qchhn0a4ocv1050u4.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendarScheduler.RunnerTests',
  );
}
